/* Textos de la landing.
   El inglés vive en index.html (main.js lo lee del propio HTML). Aquí van:
   - en: solo los textos que genera JS (errores, confirmación, countdown, .ics)
   - de: la traducción completa, localizada (no palabra por palabra) */
window.ENTRIX_I18N = {
  en: {
    "countdown.live": "Live now",
    "countdown.ended": "This webinar has ended",
    "form.loading": "Registering…",
    "err.required": "Please fill in this field.",
    "err.email": "Please enter a valid email address.",
    "err.workEmail": "Please use your work email address.",
    "err.select": "Please select an option.",
    "err.privacy": "Please accept the privacy policy.",
    "success.text": "Thanks, {name}. We'll send the link to join and a calendar invite to {email}.",
    "ics.summary": "Entrix Webinar: Beyond Revenue per MW",
    "ics.description": "How to compare battery performance more meaningfully. Online, in English. The link to join is in your confirmation email."
  },

  de: {
    "meta.title": "Mehr als Umsatz pro MW · Entrix Webinar",
    "meta.description": "Live-Webinar für BESS-Entwickler und Asset Owner: Warum sich Batteriespeicher-Performance nicht allein über den Umsatz pro MW vergleichen lässt.",
    "skip": "Zur Anmeldung springen",

    "nav.aria": "Seitenbereiche",
    "nav.why": "Hintergrund",
    "nav.speakers": "Speaker",
    "nav.topics": "Themen",
    "nav.agenda": "Agenda",
    "nav.faq": "FAQ",
    "nav.register": "Anmelden",
    "lang.aria": "Sprache",

    "strip.tag": "Live-Webinar",
    "strip.facts": "Kostenlos · Online · Englisch",
    "strip.date": "18. Nov. 2026",
    "strip.time": "Mittwoch · 11:00 bis 12:00\u00a0Uhr\u00a0MEZ",
    "countdown.label": "Beginnt in",
    "countdown.days": "Tage",
    "countdown.hours": "Std",
    "countdown.minutes": "Min",
    "countdown.seconds": "Sek",
    "countdown.live": "Jetzt live",
    "countdown.ended": "Das Webinar ist beendet",

    "intro.eyebrow": "Entrix-Webinar · BESS\u00a0Performance",
    "intro.title": "<span>Mehr als Umsatz pro\u00a0MW:</span> Batteriespeicher-Performance sinnvoller vergleichen",
    "intro.lead": "Umsatz pro MW ist eine nützliche Kennzahl, zeigt für sich allein aber nur einen Ausschnitt der Performance. Ein Entrix-Experte und ein externer Branchenexperte diskutieren mit Ihnen, worauf es beim Vergleich von Batteriespeichern sonst noch ankommt und was das für Ihre Asset-Entscheidungen bedeutet.",
    "facts.date.label": "Datum",
    "facts.date": "Mittwoch, 18. November 2026",
    "facts.time.label": "Uhrzeit",
    "facts.time": "11:00 bis 12:00 Uhr MEZ",
    "facts.format.label": "Format",
    "facts.format": "Online, auf Englisch",
    "facts.audience.label": "Für",
    "facts.audience": "BESS-Entwickler und Asset Owner",

    "form.eyebrow": "Kostenlose Anmeldung",
    "form.title": "Sichern Sie sich Ihren Platz",
    "form.firstName": "Vorname",
    "form.email": "Geschäftliche E-Mail",
    "form.company": "Unternehmen",
    "form.companyType": "Unternehmenstyp",
    "form.role": "Rolle / Funktion",
    "form.select": "Bitte auswählen…",
    "form.type.developer": "BESS-Entwickler",
    "form.type.owner": "Asset Owner",
    "form.type.other": "Sonstiges",
    "form.role.commercial": "Commercial / Business Development",
    "form.role.investment": "Investment / Asset Management",
    "form.role.technical": "Technik / Betrieb",
    "form.role.other": "Sonstiges",
    "form.privacy": "Ich akzeptiere die <a href=\"https://www.entrixenergy.com/en/privacy-policy\" target=\"_blank\" rel=\"noopener\">Datenschutzerklärung</a>.",
    "form.note": "Sie erhalten eine Bestätigungs-E-Mail mit dem Teilnahmelink und einer Kalendereinladung.",
    "form.loading": "Anmeldung läuft…",
    "cta.register": "Zum Webinar anmelden",
    "err.required": "Bitte füllen Sie dieses Feld aus.",
    "err.email": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "err.workEmail": "Bitte verwenden Sie Ihre geschäftliche E-Mail-Adresse.",
    "err.select": "Bitte wählen Sie eine Option aus.",
    "err.privacy": "Bitte akzeptieren Sie die Datenschutzerklärung.",
    "success.title": "Sie sind angemeldet",
    "success.text": "Danke, {name}. Wir senden den Teilnahmelink und eine Kalendereinladung an {email}.",
    "success.calendar": "Zum Kalender hinzufügen",
    "success.demo": "Konzept-Demo · es wurden keine Daten gesendet",
    "ics.summary": "Entrix Webinar: Mehr als Umsatz pro MW",
    "ics.description": "Batteriespeicher-Performance sinnvoller vergleichen. Online, auf Englisch. Den Teilnahmelink finden Sie in Ihrer Bestätigungs-E-Mail.",

    "why.eyebrow": "Hintergrund",
    "why.title": "Was sagt der Umsatz pro MW wirklich über die Performance eines Batteriespeichers aus?",
    "why.lead": "Diese Zahl nennt jeder, und mit ihr ist schnell klar, welcher Speicher vorne liegt. Sie erklärt aber nicht, warum der eine mehr erwirtschaftet als der andere.",
    "why.chart.title": "Eine Zahl, nur ein Teil des Bildes",
    "why.chart.label": "Schematisch",
    "why.chart.headline": "Die Kennzahl",
    "why.chart.context": "Was dahintersteckt",
    "why.dev.tag": "BESS-Entwickler",
    "why.dev.title": "Projekte vergleichen",
    "why.dev.text": "Zwei Projekte können auf dem Papier einen ähnlichen erwarteten Umsatz pro MW haben. Bevor Sie sich für eines entscheiden, sollten Sie wissen, worauf jede dieser Zahlen beruht.",
    "why.owner.tag": "Asset Owner",
    "why.owner.title": "Ein Asset im Betrieb bewerten",
    "why.owner.text": "Ein hoher Umsatz pro MW sieht nach starker Performance aus, und das kann durchaus stimmen. Die Zahl allein kann das aber nicht belegen.",

    "speakers.eyebrow": "Speaker",
    "speakers.title": "Zwei Perspektiven auf Batteriespeicher-Performance",
    "speakers.lead": "Ein Speaker kommt von Entrix, der andere bringt den Blick von außen mit.",
    "speakers.entrix.role": "Funktion folgt",
    "speakers.external.tag": "Gast",
    "speakers.external.role": "Funktion und Unternehmen folgen",

    "learn.eyebrow": "Das nehmen Sie mit",
    "learn.title": "Drei Fragen, über die wir sprechen",
    "learn.1.q": "Reicht Umsatz pro MW aus?",
    "learn.1.text": "Wann die Kennzahl ein fairer Maßstab für den Vergleich zweier Batteriespeicher ist und wann nicht.",
    "learn.2.q": "Was gehört noch ins Bild?",
    "learn.2.text": "Welchen Kontext Sie neben dem Umsatz pro MW brauchen, um die Performance eines Batteriespeichers einzuordnen.",
    "learn.3.q": "Was ändert sich für Ihre Entscheidungen?",
    "learn.3.text": "Wie die Antworten Ihre Wahl zwischen Projekten und die Bewertung laufender Assets beeinflussen.",

    "agenda.eyebrow": "Agenda",
    "agenda.title": "Der Ablauf im Überblick",
    "agenda.note": "Vorläufig · alle Zeiten MEZ",
    "agenda.1.title": "Begrüßung und Live-Umfrage",
    "agenda.1.text": "Eine kurze Einführung und eine Frage an Sie: Wie vergleichen Sie BESS-Performance heute?",
    "agenda.2.title": "Warum Umsatz pro MW allein nicht ausreicht",
    "agenda.2.text": "Was die Kennzahl abbildet und was sie offenlässt.",
    "agenda.2.tag": "Entrix-Experte",
    "agenda.3.title": "Expertendiskussion",
    "agenda.3.text": "Wie sich Batteriespeicher-Performance in der Praxis vergleichen lässt.",
    "agenda.4.title": "Live-Q&A",
    "agenda.4.text": "Ihre Fragen an die Speaker und zum Schluss, wie sich die Ideen auf Ihr eigenes Projekt übertragen lassen.",
    "agenda.both": "Beide Speaker",

    "faq.eyebrow": "FAQ",
    "faq.title": "Gut zu wissen",
    "faq.1.q": "Ist die Teilnahme kostenlos?",
    "faq.1.a": "Ja. Sie müssen sich nur anmelden.",
    "faq.2.q": "Gibt es eine Aufzeichnung?",
    "faq.2.a": "Ja. Wir schicken die Aufzeichnung und die wichtigsten Erkenntnisse an alle Angemeldeten, ob sie live dabei waren oder nicht.",
    "faq.3.q": "In welcher Sprache findet das Webinar statt?",
    "faq.3.a": "Auf Englisch.",
    "faq.4.q": "Wie nehme ich teil?",
    "faq.4.a": "Melden Sie sich auf dieser Seite an und nutzen Sie am Webinartag den Teilnahmelink aus Ihrer Bestätigungs-E-Mail.",
    "faq.5.q": "Kann ich Fragen stellen?",
    "faq.5.a": "Ja, jederzeit während des Webinars. Die Speaker greifen sie am Ende in der Live-Q&A auf.",
    "faq.6.q": "Für wen ist das Webinar gedacht?",
    "faq.6.a": "Für BESS-Entwickler und Asset Owner, vor allem aus den Bereichen Commercial, Investment, Asset Management und Business Development.",

    "cta.title": "Mehr sehen als eine Zahl",
    "cta.text": "Erfahren Sie, was hinter dem Umsatz pro MW steckt, bevor Sie die nächste Asset-Entscheidung treffen.",
    "cta.meta": "Mi · 18. Nov. 2026 · 11:00 Uhr MEZ · Online",

    "contact.eyebrow": "Fragen zum Webinar?",
    "contact.text": "Schreiben Sie uns, wenn Sie Hilfe bei der Anmeldung brauchen oder mehr über die Inhalte wissen möchten.",
    "contact.button": "Nachricht senden",

    "footer.aria": "Rechtliches",
    "footer.privacy": "Datenschutz",
    "footer.imprint": "Impressum",
    "footer.disclaimer": "Konzeptseite für die Entrix Marketing Case Study. Dies ist keine offizielle Entrix-Seite, und das Anmeldeformular übermittelt keine Daten."
  }
};
